jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:900000}
server.port=${PORT:9090}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.dev-mode=${MAIL_DEV_MODE:true}
user.service.url=${USER_SERVICE_URL:http://localhost:8081}
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5671}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VIRTUAL_HOST}
spring.rabbitmq.ssl.enabled=${SPRING_RABBITMQ_SSL_ENABLED:true}
rabbitmq.exchange.auth=auth.exchange
rabbitmq.routing-key.otp-verification=auth.otp.verification
rabbitmq.routing-key.otp-resend=auth.otp.resend
rabbitmq.routing-key.password-reset=auth.password.reset
