sonar.projectKey=patrici-a
sonar.organization=patrici-a
sonar.java.source=21
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
