package edu.eci.patricia.DOSW_patricia.entrypoints.rest.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * REST request body for the init-verification endpoint ({@code POST /api/v1/auth/init-verification}).
 * Sent by the registration service after creating the user account to trigger OTP delivery.
 */
@Schema(description = "Request body sent by the registration service to trigger OTP generation and email dispatch for a new user")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class InitVerificationRequest {

    @NotBlank(message = "Email is required")
    @Email(message = "Must be a valid email address")
    @Schema(description = "Institutional email address of the newly registered user. Must end in @mail.escuelaing.edu.co",
            example = "juan.perez@mail.escuelaing.edu.co")
    private String email;

    @NotBlank(message = "Hashed password is required")
    @Schema(description = "BCrypt-hashed password generated by the registration service. Never stored in plain text.",
            example = "$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36ZDd7ThPkXn3/MtGxqJKpq")
    private String hashedPassword;
}
