services:

  redis:
    image: redis:7-alpine
    container_name: patricia-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  auth-service:
    build: .
    container_name: patricia-auth-service
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      USER_SERVICE_URL: https://host.docker.internal:8443
    depends_on:
      - redis
    restart: unless-stopped
