package edu.eci.patricia.DOSW_patricia.application.dto.request;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Application-layer DTO for the init-verification use case.
 * Carries the user's institutional email and the BCrypt-hashed password supplied by the
 * registration service when it creates the account.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class InitVerificationRequestDto {

    /** The user's institutional email address. */
    private String email;
    /** BCrypt-hashed password generated by the registration service. */
    private String hashedPassword;
}
